### ISSUE TITLE
Suggestion to add `timeperiod` parameter to SearchCatalog

### ISSUE THREAD

**Issue by micha-silver** [zivankaraman/CDSE#7]
Hello @zivankaraman 
In the deprecated {sen2r} there was an option to filter image dates by season. This allowed to acquire images over many years, but only for certain months in each year. I think it would be a useful addition to {CDSE}. I can offer a PR for this enhancement, if you are willing to try it.
Regards, Micha

**Comment by zivankaraman** [comment]
Hello @micha-silver 
Thank you for your suggestion. It might indeed be useful to have this option. I'll take a look at it to see how it could be best implemented.
Regards, Zivan

**Comment by micha-silver** [comment]
Thanks!
I did not see any obvious way to add this "seasonal" filtering to a query for the API request. That would be optimal, but I don't see it implemented in the Scihub API. 

So, in  a fork of your project,  I added the following code to SearchCatalog.R to filter by season after the results are returned. I added a boolean parameter `seasonal` (with default FALSE) then:

```
    if (seasonal) {
        # Filter only dates between from day/month and to day/month for all years
        to_date <- lubridate::ymd(paste(lubridate::year(from),
                                         lubridate::month(to),
                                         lubridate::day(to), sep="-"))
        # Find the lag in days between from date, and to date *for the same year*
        per <- difftime(to_date, from, "days")
        if (per < 0) {
            # In case the "season" crosses over to the next year
            to_date <- lubridate::ymd(paste(lubridate::year(from)+1,
                                            lubridate::month(to),
                                            lubridate::day(to), sep="-"))
            per <- difftime(to_date, from, "days")
        }
        # Loop over all years in the original time range
        years <- seq.int(lubridate::year(from), lubridate::year(to))
        out_list <- lapply(years, function(y) {
            per_start <- lubridate::ymd(paste(y, lubridate::month(from),
                                              lubridate::day(from),
                                              sep="-"))
            per_end <- per_start + days(per)
            out_df <- out[out$acquisitionDate >= per_start &
                          out$acquisitionDate <= per_end,]
            return(out_df)
        })
        out_seasonal <- do.call(rbind, out_list)
        return(out_seasonal)
    }
```

(This will work only if your parameter  `as_data_frame` is TRUE)

Best, Micha

**Comment by zivankaraman** [comment]
Thank you so much for the nice code!

The Scihub API has been decommissioned recently. The current API uses the STAC protocol, which allows querying for a single time range at a time only. So the filtering can't be done on the server side but must be implemented by the client.

One way is to retrieve all the data and filter it, as you did. The other would be to create a list of time ranges of interest, query each time range separately in a loop, and then combine the results. I plan to implement both in a future version of the package.

I prefer keeping functions small, simple and modular, so rather than adding an extra argument I would add an extra function that would produce the same result as your code.
So, one would have to do something like 
`seasonalCatalog = SearchCatalog(…, from, to, …) |> SeasonalFilter(from, to)`
This would also allow for applying several filters from a single query result if needed.

Thanks again for your suggestion and the code.
Best, Zivan

**Comment by micha-silver** [comment]
Your willingness to take up this suggestion is greatly appreciated!

I think that filtering after getting back the response will not be difficult. But I did see that the {rstac} package, for example,  implements an `ext_filter()` function with some extended filtering options:
[CQL2](https://github.com/brazil-data-cube/rstac#cql2-query-filter)

Regards, Micha

**Comment by zivankaraman** [comment]
You are right, there is the `rstac` package that has some interesting features.

When developing the CDSE package, I started by using the `rstac` package, but I encountered a problem with the response pagination. The CDSE API pagination is not fully compatible with STAC standard, so I had to develop my own STAC query function. I can extend it to allow for additional CQL2 filters, but it turns out that although the STAC protocol allows for querying (or, to be more precise, filtering on) several time ranges, the CDSE implementation does not (yet?) support this functionality. Currently, for the Sentinel 2 imagery, the only filtering option is cloud cover (well, this is probably the most interesting one, too). 

So for the time being, we can't rely on the CDSE STAC API to obtain the list of available seasonal images. 

Best regards, Zivan

**Comment by micha-silver** [comment]
I'll look forward to testing once you have something working :-)

**Comment by zivankaraman** [comment]
The new release is (finally) available on Github

**Comment by zivankaraman** [comment]
Hi,
I have finally released an updated version of the package on GitHub, hope
you'll find it useful.
Best,
Zivan

**Comment by micha-silver** [comment]
Great, I'll give it  a try this week.

**Comment by micha-silver** [comment]
This new feature looks good!
I gave it a try on one of our study areas, and it worked fine. 

n.b. I have incorporated {CDSE} into the package we are working on - [rOPTRAM](https://gitlab.com/rsl-bidr/roptram). I have added this new SeasonFilter to our dev branch. Once you go ahead and push the new feature to CRAN, I'll also merge into our main branch.

I Appreciate your help.

**Comment by zivankaraman** [comment]
Thank you for your feedback. I will wait for a few days to collect more feedback on the current version and fix any issues that may arise before submitting it to CRAN. CRAN does not appreciate frequent submissions, which is why I am taking this approach. 
Best regards, Zivan.

**Comment by zivankaraman** [comment]
FYI, the new version of the package is now available on CRAN.
Best regards, Zivan

**Comment by micha-silver** [comment]
:clap:  :clap:
Thanks!
